-- STUDENT table
CREATE TABLE STUDENT (ROLL_NO INT PRIMARY KEY, NAME VARCHAR(100),DEPARTMENTCODE VARCHAR(10), DOB DATE, EMAIL VARCHAR(100), ADDRESS VARCHAR(200));

-- COURSE table
CREATE TABLE COURSE ( CCODE VARCHAR(10) PRIMARY KEY, CNAME VARCHAR(100),DEPARTMENTCODE VARCHAR(10));

-- ENROLL table
CREATE TABLE ENROLL (ROLLNO INT, COURSECODE VARCHAR(10),SEMESTER INT,GRADE CHAR(2),PRIMARY KEY (ROLLNO, COURSECODE, SEMESTER),FOREIGN KEY (ROLLNO) REFERENCES STUDENT(ROLL_NO),FOREIGN KEY (COURSECODE) REFERENCES COURSE(CCODE));

-- TEXTBOOK table
CREATE TABLE TEXTBOOK (COURSECODE VARCHAR(10),SEMESTER INT,BOOK_ISBN VARCHAR(20),PRIMARY KEY (COURSECODE, SEMESTER, BOOK_ISBN),FOREIGN KEY (COURSECODE) REFERENCES COURSE(CCODE),FOREIGN KEY (BOOK_ISBN) REFERENCES BOOKDETAILS(BOOK_ISBN));

-- BOOKDETAILS table
CREATE TABLE BOOKDETAILS (BOOK_ISBN VARCHAR(20) PRIMARY KEY,TITLE VARCHAR(200),PUBLISHER VARCHAR(100),AUTHOR VARCHAR(100));

-- Add column in BOOKDETAILS table
ALTER TABLE BOOKDETAILS ADD PRICE DECIMAL(10,2);

ALTER TABLE STUDENT DROP COLUMN ADDRESS;

TRUNCATE TABLE COURSE;

DROP TABLE COURSE;



