-- ONE EXAMPLE OF EACH TABLE, MAKE 10 ENTRIES OF EACH TABLE LIKE GIVEN BELOW

-- STUDENT table
INSERT INTO STUDENT (ROLL_NO, NAME, DEPARTMENTCODE, DOB, EMAIL, ADDRESS)
VALUES (1, 'Alice', 'CSE', '2002-05-12', 'alice@example.com', 'Pune');

-- COURSE table
INSERT INTO COURSE (CCODE, CNAME, DEPARTMENTCODE)
VALUES ('CSE101', 'Database Systems', 'CSE');

-- ENROLL table
INSERT INTO ENROLL (ROLLNO, COURSECODE, SEMESTER, GRADE)
VALUES (1, 'CSE101', 2, 'A');

-- BOOKDETAILS table
INSERT INTO BOOKDETAILS (BOOK_ISBN, TITLE, PUBLISHER, AUTHOR, PRICE)
VALUES ('ISBN001', 'Database Concepts', 'Pearson', 'Elmasri', 500);

-- TEXTBOOK table
INSERT INTO TEXTBOOK (COURSECODE, SEMESTER, BOOK_ISBN)
VALUES ('CSE101', 2, 'ISBN001');

--STEP 2:
UPDATE BOOKDETAILS SET PRICE = PRICE + 100 WHERE PUBLISHER_YEAR > 2005;

--STEP 3:
DELETE FROM BOOKDETAILS WHERE EDITION = 'First';

--STEP 4:
UPDATE STUDENT
SET EMAIL = 'newemail@example.com' WHERE ROLL_NO = 1;   -- Replace 1 with the user-specified roll number

--STEP 5:
SELECT S.ROLL_NO, S.NAME, S.DEPARTMENTCODE, S.EMAIL FROM STUDENT S JOIN ENROLL E ON S.ROLL_NO = E.ROLLNO JOIN COURSE C ON E.COURSECODE = C.CCODE WHERE C.DEPARTMENTCODE = 'CSE'  AND E.SEMESTER = 2;



